valine:
  enable: true
  appid: Q4LdY4IYxiewjGYc9EIEepy1-9Nh9j0Va
  appkey: nibhEo9vS0W8SFPvKS2uYgEQ
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki 是否开启邮箱提醒
  verify: false # Verification code   是否开启验证码
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
